# Generated by Django 5.1.7 on 2025-04-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="description",
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="email",
            field=models.EmailField(default="Example Company", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="industry",
            field=models.CharField(default="Example Company", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="location",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="company_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
