# Generated by Django 5.1.7 on 2025-03-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_delete_jobapplication2"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="official_website",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
