# Generated by Django 5.1.7 on 2025-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_job_official_website"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="official_website",
        ),
        migrations.AddField(
            model_name="job",
            name="apply_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="application_method",
            field=models.CharField(
                choices=[
                    ("PLATFORM", "Applied via Platform"),
                    ("LINK", "Applied via External Link"),
                ],
                default="PLATFORM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="external_link_used",
            field=models.URLField(blank=True, null=True),
        ),
    ]
