# Generated by Django 5.1.7 on 2025-03-11 19:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_job_official_website_job_apply_link_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
            },
        ),
        migrations.AlterModelOptions(
            name="jobapplication",
            options={
                "ordering": ["-applied_on"],
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications",
            },
        ),
        migrations.AddField(
            model_name="job",
            name="experience_years",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50),
                ],
                verbose_name="Years of Experience Required",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active Job"),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="cover_letter",
            field=models.TextField(blank=True, null=True, verbose_name="Cover Letter"),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="resumes/", verbose_name="Resume"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("REVIEWED", "Reviewed"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="Application Status",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="apply_link",
            field=models.URLField(blank=True, null=True, verbose_name="Apply Link"),
        ),
        migrations.AlterField(
            model_name="job",
            name="category",
            field=models.CharField(
                choices=[
                    ("IT", "Information Technology"),
                    ("HR", "Human Resources"),
                    ("FINANCE", "Finance"),
                    ("MARKETING", "Marketing"),
                    ("SALES", "Sales"),
                    ("ENGINEERING", "Engineering"),
                    ("DESIGN", "Design"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
                verbose_name="Job Category",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.CharField(max_length=255, verbose_name="Company Name"),
        ),
        migrations.AlterField(
            model_name="job",
            name="contact_email",
            field=models.EmailField(max_length=254, verbose_name="Contact Email"),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="deadline",
            field=models.DateField(verbose_name="Application Deadline"),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(verbose_name="Job Description"),
        ),
        migrations.AlterField(
            model_name="job",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("HIGH_SCHOOL", "High School"),
                    ("DIPLOMA", "Diploma"),
                    ("BACHELORS", "Bachelor's Degree"),
                    ("MASTERS", "Master's Degree"),
                    ("PHD", "PhD"),
                    ("OTHER", "Other"),
                ],
                default="BACHELORS",
                max_length=50,
                verbose_name="Education Level",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="job_images/", verbose_name="Job Image"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(max_length=255, verbose_name="Job Location"),
        ),
        migrations.AlterField(
            model_name="job",
            name="required_skills",
            field=models.TextField(verbose_name="Required Skills"),
        ),
        migrations.AlterField(
            model_name="job",
            name="requirements",
            field=models.TextField(verbose_name="Job Requirements"),
        ),
        migrations.AlterField(
            model_name="job",
            name="responsibilities",
            field=models.TextField(verbose_name="Job Responsibilities"),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Salary",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Job Title"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="application_method",
            field=models.CharField(
                choices=[
                    ("PLATFORM", "Applied via Platform"),
                    ("LINK", "Applied via External Link"),
                ],
                default="PLATFORM",
                max_length=10,
                verbose_name="Application Method",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="applied_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Applied On"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="external_link_used",
            field=models.URLField(
                blank=True, null=True, verbose_name="External Link Used"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.job",
                verbose_name="Job Applied For",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Applicant",
            ),
        ),
    ]
