# Generated by Django 6.0 on 2025-03-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="apply_link",
            field=models.URLField(
                blank=True, help_text="Link to apply externally", null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="education_level",
            field=models.CharField(
                help_text="Minimum education level required", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="required_skills",
            field=models.TextField(help_text="Comma-separated list of required skills"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="external_link_used",
            field=models.URLField(
                blank=True, help_text="External link used for application", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="education_level",
            field=models.CharField(
                blank=True,
                help_text="User's highest education level",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="interests",
            field=models.TextField(blank=True, help_text="User's interests", null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="qualifications",
            field=models.TextField(
                blank=True, help_text="User's qualifications", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="skills",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of skills", null=True
            ),
        ),
    ]
