# Generated by Django 6.0 on 2025-03-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_job_apply_link_alter_job_education_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="User's profile picture",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
