# Generated by Django 6.0 on 2025-03-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_userprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="User's profile photo",
                null=True,
                upload_to="photos/",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="resume",
            field=models.FileField(
                blank=True,
                help_text="User's resume (PDF or DOCX)",
                null=True,
                upload_to="resumes/",
            ),
        ),
    ]
