# Generated by Django 6.0 on 2025-03-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_userprofile_photo_userprofile_resume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="photo",
        ),
    ]
