# Generated by Django 6.0 on 2025-03-20 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_userprofile_avatar_alter_userprofile_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="User's profile picture",
                null=True,
                upload_to="avatars/",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Preferred job category",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="education_level",
            field=models.CharField(
                blank=True,
                help_text="User's highest education level",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="interests",
            field=models.TextField(blank=True, help_text="User's interests", null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.CharField(
                blank=True, help_text="User's location", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="qualifications",
            field=models.TextField(
                blank=True, help_text="User's qualifications", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="resume",
            field=models.FileField(
                blank=True,
                help_text="User's resume (PDF or DOCX)",
                null=True,
                upload_to="resumes/",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="skills",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of skills", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
