# Generated by Django 5.1.7 on 2025-04-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_userprofile_avatar_alter_userprofile_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="qualifications",
        ),
        migrations.AlterField(
            model_name="job",
            name="requirements",
            field=models.TextField(help_text="Skills"),
        ),
    ]
