# Generated by Django 5.1.7 on 2025-04-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_companyprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanyProfile",
        ),
    ]
