# Generated by Django 5.1.7 on 2025-04-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_delete_companyprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SELECTED", "Selected"),
                    ("REJECTED", "Rejected"),
                    ("INTERVIEW", "Interview Scheduled"),
                ],
                default="PENDING",
                help_text="Current status of the job application",
                max_length=10,
            ),
        ),
    ]
