# Generated by Django 5.1.7 on 2025-05-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_jobapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="interview_message",
            field=models.TextField(
                blank=True,
                help_text="Additional message or instructions for the interview",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="meeting_link",
            field=models.URLField(
                blank=True,
                help_text="Meeting link for interview (only if status is INTERVIEW)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="application_method",
            field=models.CharField(
                choices=[
                    ("PLATFORM", "Applied via Platform"),
                    ("LINK", "Applied via External Link"),
                ],
                default="PLATFORM",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="applied_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="external_link_used",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPLIED", "Applied"),
                    ("IN_REVIEW", "In Review"),
                    ("INTERVIEW", "Interview"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="APPLIED",
                max_length=20,
            ),
        ),
    ]
