# Generated by Django 5.1.7 on 2025-05-14 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_jobapplication_interview_message_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="interview_message",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="meeting_link",
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="interview_meeting_link",
            field=models.URLField(
                blank=True,
                help_text="Interview meeting link (e.g., Zoom/Google Meet)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="application_method",
            field=models.CharField(
                choices=[
                    ("PLATFORM", "Applied via Platform"),
                    ("LINK", "Applied via External Link"),
                ],
                default="PLATFORM",
                help_text="Method used to apply for the job",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="applied_on",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the application was submitted",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="external_link_used",
            field=models.URLField(
                blank=True, help_text="External link used for application", null=True
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPLIED", "Applied"),
                    ("IN_REVIEW", "In Review"),
                    ("INTERVIEW", "Interview"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="APPLIED",
                help_text="Current status of the job application",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject of the message", max_length=255
                    ),
                ),
                ("body", models.TextField(help_text="Content of the message")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Whether the message has been read"
                    ),
                ),
                (
                    "job_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="app.jobapplication",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
