# Generated by Django 5.1.7 on 2025-05-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_remove_jobapplication_interview_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="interview_meeting_link",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
