# Generated by Django 5.1.7 on 2025-05-14 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_remove_jobapplication_interview_meeting_link_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(help_text="Message content")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "read",
                    models.BooleanField(
                        default=False, help_text="Whether the user has read the message"
                    ),
                ),
                (
                    "job_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="app.jobapplication",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        help_text="Interview meeting link (e.g., Zoom/Google Meet)"
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        help_text="Scheduled date and time for the interview"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview",
                        to="app.jobapplication",
                    ),
                ),
            ],
        ),
    ]
