# Generated by Django 5.1.7 on 2025-05-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_applicationmessage_interview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interview",
            name="job_application",
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="interview_meeting_link",
            field=models.URLField(
                blank=True,
                help_text="Meeting link for interview (e.g., Zoom, Google Meet)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="interview_message",
            field=models.TextField(
                blank=True,
                help_text="Message or instructions about the interview",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="ApplicationMessage",
        ),
        migrations.DeleteModel(
            name="Interview",
        ),
    ]
